# Generated by Django 3.0.6 on 2020-06-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='grade_denominator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='grade_numerator',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='essay',
            name='marked_body',
            field=models.TextField(default=''),
        ),
    ]
