# Generated by Django 3.0.7 on 2020-06-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0004_essay_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='citation_type',
            field=models.CharField(choices=[('APA', 'APA'), ('MLA', 'MLA')], default='None', max_length=150),
        ),
    ]
