# Generated by Django 2.2.13 on 2020-06-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader_app', '0005_auto_20200614_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='teachers',
            field=models.TextField(default='{"period_7_teacher": "", "period_2_teacher": "", "period_5_teacher": "", "period_6_teacher": "", "period_1_teacher": "", "period_3_teacher": "", "period_4_teacher": ""}'),
        ),
    ]
